### ISSUE TITLE
Plugin cause lag

### ISSUE THREAD

**Issue by andris155** [KodingDev/TechFun#1]
![jegyzet](https://user-images.githubusercontent.com/8324198/41157678-e41df168-6b26-11e8-9bd7-7d64cfb520dd.png)

**Comment by KodingKing1** [comment]
Sorry for the late response, however this plugin is a bit old and will probably not be updated for a while. I have moved on to working at @hyperiumclient and am focusing on that in my free time. Thanks for giving the time to post this, but I am afraid it has become lower on my priorities list.
